volumes:
  redis_data:
  mysql_varlib: 
  dataprotection-keys:

services:
  redis:
    container_name: rmap-redis
    image: redis:7.4
    command: redis-server --requirepass $DOTENV_REDIS_PASSWORD --save 20 1 --loglevel warning
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mysql:
    container_name: rmap-mysql
    image: ghcr.io/reconmap/rest-api-db:latest
    restart: unless-stopped
    volumes:
      - mysql_varlib:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: reconmuppet
    healthcheck:
      test: "mysql -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD mysql -e 'SELECT 1;'"
      interval: 5s
      timeout: 10s
      retries: 5

  keycloak:
    container_name: rmap-keycloak
    image: ghcr.io/reconmap/keycloak-custom:latest
    command: "start --hostname-strict=false --proxy-headers xforwarded --http-enabled true --import-realm"
    # See https://www.keycloak.org/server/all-config
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL_HOST: mysql 
      KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: keycloaker
      KC_DB_PASSWORD: keycloaked
      VAR_WEB_CLIENT_URL: "http://localhost:5500"
      VAR_ADMIN_CLIENT_SECRET: "r2TO5uRy0RlpB5TRI6GvvXtBKxUCaaz0"
      VAR_RECONMAPD_CLIENT_SECRET: "VH8HDKabxlTpnpPkEgLlTq2dEanedEGC"
      VAR_API_CLIENT_SECRET: "I0jppD5zSIXuBAql31zrXfe5OAa0nvyE"
    restart: unless-stopped
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"]
      interval: 30s
      timeout: 10s
      retries: 10
    depends_on:
        mysql:
            condition: service_healthy

  web-client:
    container_name: rmap-web-client
    image: ghcr.io/reconmap/web-client:latest
    restart: unless-stopped
    volumes:
      - ./config-ui.json:/usr/share/nginx/html/config.json:ro
    ports:
      - "5500:5500"
    depends_on:
      keycloak:
        condition: service_healthy

  api:
    container_name: rmap-api
    image: ghcr.io/reconmap/rest-api:latest
    restart: unless-stopped
    volumes:
      - "./config-api.json:/var/www/webapp/config.json"
      - "./logs:/var/www/webapp/logs/"
      - "./data:/var/www/webapp/data/"
    ports:
      - "5510:5510"
    depends_on:
        mysql:
            condition: service_healthy

  ngapi:
    container_name: rmap-ngapi
    image: ghcr.io/reconmap/ng-api:latest
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - "./config-ngapi.json:/App/appsettings.json"
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys
    ports:
      - "5253:5253"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5253

  agent:
    container_name: rmap-agent
    image: ghcr.io/reconmap/agent:latest
    restart: unless-stopped
    ports:
      - "5520:5520"
    volumes:
      - "./config-agent.json:/root/.config/reconmap/config-reconmapd.json"
    command: /app/reconmapd run 
    environment:
      RMAP_KEYCLOAK_DEBUG: false
      RMAP_KEYCLOAK_SKIP_TLS_VERIFY: true
  
