apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: web-client
  name: web-client
  namespace: nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-client
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/reconmap-default: "true"
        io.kompose.service: web-client
    spec:
      containers:
        - image: quay.io/reconmap/web-client:master
          name: rmap-web-client
          ports:
            - containerPort: 5500
              hostPort: 5500
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/environment.js
              subPath: environment.js
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: web-client-configmap
